
version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=./venv

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./storage:/data/db 

volumes:
  storage: 



